replicaCount: 1
image:
  repository: andersonmarquesdocker/${{values.app_name}}
  pullPolicy: IfNotPresent
  tag: ${{values.app_name}}-${{values.app_env}}-latest

resources:
  requests:
    cpu: 40m
    memory: 40Mi